name: Build-docs

on:
  push:
    branches:
    - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: bash build-docs.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GX_TOKEN }}
